# Generated by Django 6.0.2 on 2026-02-22 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_device_celltower_batterylog_deviceevent_geofence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownWiFiEnvironment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bssids', models.JSONField(default=list, help_text='List of string BSSIDs associated with this environment')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_wifi_envs', to='telemetry.device')),
            ],
        ),
    ]
