# Generated by Django 6.0.2 on 2026-02-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_knownwifienvironment'),
    ]

    operations = [
        migrations.AddField(
            model_name='celltower',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
