# Generated by Django 6.0.2 on 2026-02-22 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_celltower_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='last_status',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.CreateModel(
            name='GeoFenceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_logs', to='telemetry.device')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='telemetry.geofence')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
