# Generated by Django 6.0.2 on 2026-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_geofence_last_status_geofencelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='zone_type',
            field=models.CharField(choices=[('SAFE', 'Safe Zone'), ('DANGER', 'Danger Zone')], default='SAFE', max_length=10),
        ),
    ]
