# Generated by Django 6.0.2 on 2026-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_geofence_zone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='polygon',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
