# Generated by Django 6.0.2 on 2026-02-24 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_geofence_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='primary_mcc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='primary_mnc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='primary_operator_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='primary_operator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='simlog',
            name='mcc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simlog',
            name='mnc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simlog',
            name='operator_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='simlog',
            name='sim_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='simlog',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SimSecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SIM_REMOVED', 'SIM Removed'), ('SIM_CHANGED', 'SIM Changed'), ('COUNTRY_CHANGED', 'Country Changed'), ('NETWORK_MISMATCH', 'Network Mismatch'), ('SUSPICIOUS_SWITCHING', 'Suspicious Switching')], max_length=50)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_security_events', to='telemetry.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
