# Generated by Django 5.0.3 on 2026-06-13 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0008_device_primary_mcc_device_primary_mnc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='watched_by',
            field=models.ManyToManyField(blank=True, help_text='Users granted read-only tracking access via 6-digit code', related_name='watched_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
